### ISSUE TITLE
Durch das Redesign hat sich das Format und der Export von iTunes Connect verändert

### ISSUE THREAD

**Issue by ServusJon** [dasdom/CreateAppStoreBill#4]
Leider lässt sich nicht wie gewohnt die Werte in die factors.txt wie beschrieben kopieren, da Apple das geändert hat. Wie kann ich es mit dem neuen Export von Apple machen?

Danke

**Comment by Elwisz** [comment]
@ServusJon Maybe https://github.com/fedoco/apple-slicer is relevant for you?
